apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-erickbalboaeb-app
  labels:
    app: student-erickbalboaeb-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-erickbalboaeb-app
  template:
    metadata:
      labels:
        app: student-erickbalboaeb-app
    spec:
      containers:
        - name: student-erickbalboaeb-app
          image: us-central1-docker.pkg.dev/devsecops-lab-464018/student-erick-balboa-eb/student-erickbalboaeb-app:latest
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
